[build]
  base = ""
  publish = "/"
  command = ""

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/ascension/*"
  to = "/THE_ASCENSION_PROJECT/:splat"
  status = 200

[[redirects]]
  from = "/manifesto-project/*"
  to = "/MANIFESTO-PROJECT/:splat"
  status = 200